baseurl = "http://www.client9.com"
title = "Digitial Sanitation Engineering"
languageCode = "en-us"
copyright = "Copyright &copy; 2008 - 2015, Nick Galbreath. All Rights Reserved."
MetaDataFormat = "yaml"

[author]
    name = "Nick Galbreath"

[indexes]
    tag = "tags"
    topic = "topics"
