# config.toml

baseurl = "http://www.client9.com/"
title = "Nick Galbreath"
languageCode = "en-US"
MetaDataFormat = "toml"
paginate = 10
PaginatePath = "/"
theme="vienna"

[author]
    name = "Nick Galbreath"

[permalinks]

    # Permalink format for pages.
     page = "/:title/"

    # Permalink format for blog posts.
    post = "/article/:title/"

[params]
    # Social accounts. Link to these accounts are displayed in the header and
    # footer.
    twitter = "@NGalbreath"
    github = "client9"
    linkedin = "nick-galbreath-1890794"
    # Disqus shortname
    #disqus = "Your disqus shortname"
    # Google Analytics API key.
    ga_api_key = "UA-33553605-1"
    # Mixpanel API key.
    # mixpanel_api_key = "Your Mixpanel API key"
    author = "Nick Galbreath"
    avatar = "/path/to/avatar"
    contact = "Your contact link (ex. mailto:foo@example.com)"
    bio = "Your short bio"
    # Short subtitle/tagline. This is displayed in the header.
    subtitle = "CTO/Founder <a href=https://www.signalsciences.com style='color:rgba(255, 255, 255, 0.7)'/>Signal Sciences</a>"
    themecolor = "#hexcolor" # Defines the tab color in Chrome for Android.

[Social]
  twitter = "NGalbreath"


